### ISSUE TITLE
大佬你好我测试了一下我们学校的

### ISSUE THREAD

**Issue by weixiabing** [Void-JackLee/ZFCourseTakingAssistant#1]
大佬你好我测试了一下我们学校的 教务系统
![image](https://user-images.githubusercontent.com/13848491/151510125-5e845312-f48c-4eb9-b087-a8477cdf81b2.png)
能够使用 但显示的不是所有课程
我想选的课找不到 这是什么原因导致的 
如图 我想找一节C2392011的课 但是列表里没有
有什么解决办法吗

**Comment by weixiabing** [comment]
好像是选修课抢不了

**Comment by Void-JackLee** [comment]
是这样的，我上面能显示的应该都会在下面的列表里，如果下面没有上没也不会有。你要找的这个课，在不开插件的情况下能**不通**过搜索，通过浏览列表找到吗？

**Comment by weixiabing** [comment]
是能够找到的
我查了一下 上面那个列表的课都是主修课程
![image](https://user-images.githubusercontent.com/13848491/151651481-1e56e4aa-f4f4-4999-afbb-50de9a15c44a.png)
其他三个（通识选修课，体育分项，特殊课程）没有包含进去
![image](https://user-images.githubusercontent.com/13848491/151651571-72d4239d-0ff8-4503-9f86-e35e7341217b.png)

**Comment by Void-JackLee** [comment]
已解决，是每页加载的课程数太少的原因。
