### ISSUE TITLE
feature request ：一键教学评价

### ISSUE THREAD

**Issue by i-CraftY** [Void-JackLee/ZFCourseTakingAssistant#2]
老哥~~是院长啊，真羡慕技术大佬~~，能不能增加教学评价功能
相关项目：https://github.com/Srpihot/flatter-teacher
因为这次不知道有第二轮评价，浪费了好多时间呢🙁

**Comment by Void-JackLee** [comment]
啊这，我电脑上有，我觉得那个太简单了没啥技术含量就没放进去，你直接jquery写一下呗，很简单的

**Comment by OopsSnap** [comment]
> 啊这，我电脑上有，我觉得那个太简单了没啥技术含量就没放进去，你直接jquery写一下呗，

**Comment by i-CraftY** [comment]
啊这😂
