### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by ljcyt** [Void-JackLee/ZFCourseTakingAssistant#3]
大佬我用了你的这个项目，很好用但是有一点就是他需要等网页加载好了，插件才能加载出课程信息，所以有可能在加载的这段时间他就被抢完了。我想问一下有没有可能在参加里面加入一个框里面写想选的课的名称然后到了就自动开始抢。

**Comment by Void-JackLee** [comment]
你完全可以在系统开放之前（提前5分钟左右）就进去，这时候足够插件加载了，之后你再选好你要的课，到时间了直接按抢课就好了（提前按的话会提示抢课失败）

**Comment by ljcyt** [comment]
我们学校不提前开启通道，他是到了开抢的点才打开抢课通道😂。我还以为其他学校也这样。感谢你的回复。

**Comment by Void-JackLee** [comment]
提前练网页都打不开吗？只要能打开网页就有办法

**Comment by Void-JackLee** [comment]
理论上如果真的打不开，我这个脚本也是可以的，就是你得知道每个课的名字，然后模糊匹配一下，或许你可以改改代码

**Comment by ljcyt** [comment]
能打开抢课的网页，但是他提示不在抢课阶段，请联系管理员。

**Comment by Void-JackLee** [comment]
那就可以用啊

**Comment by Void-JackLee** [comment]
你提前选好，到了时间在点“抢”就好了

**Comment by ljcyt** [comment]
脚本他获取不到课程信息，没有像开始了那样能显示出所有能抢的课。

**Comment by ljcyt** [comment]
脚本他取不到课程信息，没有像开始抢课后那样能显示出所有能抢的课。

**Comment by Void-JackLee** [comment]
那你们学校这个目前这个脚本可能搞不来，因为我们学校是一开始可以获取到课程信息的，只是抢不了，开始了才可以抢，所以就可以提前用脚本选好，到点了再选，那你或许可以改改代码模糊匹配一下

**Comment by ljcyt** [comment]
你们学校体育选修也是能提前看到吗?

**Comment by ljcyt** [comment]
你们学校体育选修也是能提前看到吗?

**Comment by Void-JackLee** [comment]
没啥印象了，我记得是和通识课放到一块的

**Comment by ljcyt** [comment]
哦哦，那估计就是我们学校的问题了，谢谢你的回复。

**Comment by ljcyt** [comment]
大佬我发现我现在向选课网页发送搜索课的请求还能获取到，我想会不会是因为脚本里面的请求方式和我们学校的不一样导致的啊

**Comment by ljcyt** [comment]
我不太懂这个油猴脚本可能描述有一些偏差，请见谅

**Comment by ljcyt** [comment]
![Screenshot_2023-06-08-00-24-24-08_265eefe1b4d950c11f237ceaad3e5729.jpg](https://github.com/Void-JackLee/ZFCourseTakingAssistant/assets/97516877/af762534-5fbc-4ccb-9fba-894031a8c955)![Screenshot_2023-06-08-00-24-19-17_265eefe1b4d950c11f237ceaad3e5729.jpg](https://github.com/Void-JackLee/ZFCourseTakingAssistant/assets/97516877/994898c0-d575-44f7-addb-5ba5a48ce8be)

**Comment by ljcyt** [comment]
昨天学校只关闭了网站人口，接口没关，现在接口也关了😭
